import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import "../styles/login.css";
import "../styles/dashboard.css";
import "../styles/table.css";
import "../styles/modal.css";
import "../styles/responsive.css";


/* CONFIGURACIÓN DE FUENTES
   Define las fuentes principales utilizadas en
   toda la aplicación. */

const geistSans = Geist({

  variable: "--font-geist-sans",
  subsets: ["latin"],

});

const geistMono = Geist_Mono({

  variable: "--font-geist-mono",
  subsets: ["latin"],

});


/* METADATOS
   Información general de la aplicación utilizada
   por Next.js. */

export const metadata: Metadata = {

  title: "Create Next App",
  description: "Generated by create next app",

};


/* LAYOUT PRINCIPAL
   Envuelve toda la aplicación y aplica las fuentes,
   estilos globales y estructura base del documento. */

export default function RootLayout({

  children,

}: Readonly<{

  children: React.ReactNode;

}>) {

  return (

    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}

    >

      <body className="min-h-full flex flex-col">

        {/* Contenido de la aplicación */}

        {children}

      </body>

    </html>

  );

}